---
- name: Initialise the RHEL Health Check
  hosts: localhost
  roles:
    - hardware_certification_matrix_check
    - network_cards_check
    - disk_drives_check
    - storage_check
    - rhel_version_check
    - last_update_check
    - password_policy
    - selinux_check
    - installed_rpm_check
    - grub_check
  tasks:
    - name: Generate the RHEL Health Check Report
      ansible.builtin.template:
        src: ./rhel_hc_report.j2
        dest: /tmp/rhel_hc_report_"{{ ansible_date_time.time }}_{{ ansible_date_time.date }}"


    