---
# tasks file for ./roles/firewall_check
- name: Register firewallD status *Don't worry if this fails*
  ansible.builtin.command: iptables -L
  register: result_firewall
  ignore_errors: true


- name: Describe firewall configuration
  become: true 
  ansible.builtin.command: iptables -L 
  register: result_firewall_success
  when: result_firewall is succeeded

- name: Notify that firewall configuration is failed
  become: true
  ansible.builtin.command: echo "Firewalls are not enabled or active"
  register: result_firewall_failed
  when: result_firewall is failed









