---
# tasks file for ./roles/firewall_check
- name: Register firewallD status *Don't worry if this fails*
  ansible.builtin.command: firewall-cmd --list-all
  register: result_firewall
  ignore_errors: true


- name: Describe FirewallD if successful
  become: true 
  ansible.builtin.command: firewall-cmd --list-all 
  register: result_firewall_success
  when: result_firewall is succeeded

- name: Notify FirewallD is failed
  become: true
  ansible.builtin.command: echo "FirewallD is not enabled or active"
  register: result_firewall_failed
  when: result_firewall is failed









