---
# tasks file for ./roles/disk_drives_check

# - name: Debug all devices
#   ansible.builtin.debug:
#     var: hostvars[inventory_hostname].ansible_mounts

# - name: Install S.M.A.R.T.
#   ansible.builtin.dnf:
#     name: smartmontools
#     state: present

- name: Find errors in the system log files
  ansible.builtin.shell: dmesg -T | grep error
  become: true
  register: result_error_logs


