---
# tasks file for ./roles/installed_rpm_check
- name: Count the number of locally installed RPM packages. *This might take a while*
  ansible.builtin.shell: rpm -Va | wc -l
  register: result_rpm_count
