---
# tasks file for ./roles/hardware_certification_matrix_check

# Hardware Certification Matrix
    - name: Find the system manufacturer
      ansible.builtin.command: dmidecode --string system-manufacturer
      changed_when: false
      become: true
      register: result_system_manufacturer

    - name: Find the system product name
      ansible.builtin.command: dmidecode --string system-product-name
      changed_when: false
      become: true
      register: result_system_product_name

    - name: Find the system version
      ansible.builtin.command: dmidecode --string system-version
      changed_when: false
      become: true
      register: result_system_version
  
