---
# tasks file for .roles/teaming_check
- name: Describe network device status
  become: true
  ansible.builtin.command: ifconfig -a
  register: result_device_status

- name: Verify current bonding mode
  become: true
  ansible.builtin.command: cat /sys/class/net/bond0/bonding/mode
  register: result_bonding_mode