---
# tasks file for ./roles/failed_services_check
- name: Collect any error or failed messages registered in the last day
  become: true
  ansible.builtin.shell: service --status-all | grep -v running
  register: result_failed_services
